------------------------------1.1---------------------------
drop sequence SEQ_A2ERROREVENT;
create sequence SEQ_A2ERROREVENT;
/
Drop table A2ERROREVENT;
/
create table A2ERROREVENT (
ERRORID INTEGER,
SOURCE_ROWID ROWID,
SOURCE_TABLE VARCHAR2(30),
ERRORCODE INTEGER,
FILTERID INTEGER,
DATETIME DATE,
ACTION VARCHAR2(6),
CONSTRAINT ERROREVENTACTION
CHECK (ACTION IN ('SKIP','MODIFY'))
);
/
------------------------------1.2--------------------------
DROP SEQUENCE SEQ_DWPROD;
CREATE SEQUENCE SEQ_DWPROD; 
/
DROP SEQUENCE SEQ_DWSALE;
CREATE SEQUENCE SEQ_DWSALE;
/
DROP SEQUENCE SEQ_DWCUST;
CREATE SEQUENCE SEQ_DWCUST;
/
DROP TABLE DWPROD;
DROP TABLE DWCUST;
DROP TABLE DWSALE;
/
create table DWPROD (
    DWPRODID INTEGER,
    DWSOURCETABLE VARCHAR2(30),
    DWSOURCEID INTEGER,
    PRODNAME VARCHAR2(130),
    PRODCATNAME VARCHAR2(40),
    PRODMANUNAME VARCHAR2(40),
    PRODSHIPNAME VARCHAR2(40)
);
/
create table DWCUST(
    DWCUSTID INTEGER,
    DWSOURCEIDBRIS INTEGER,
    DWSOURCEIDMELB INTEGER,
    FIRSTNAME VARCHAR2(40),
    SURNAME VARCHAR2(40),
    GENDER VARCHAR2(20),
    PHONE VARCHAR2(30),
    POSTCODE NUMBER(4,0),
    CITY VARCHAR2(60),
    STATE VARCHAR2(20),
    CUSTCATNAME VARCHAR2(40)
);
/
create table DWSALE(
    DWSALEID INTEGER,
    DWCUSTID INTEGER,
    DWPRODID INTEGER,
    DWSOURCEIDBRIS INTEGER,
    DWSOURCEIDMELB INTEGER,
    QTY NUMBER(2,0),
    SALE_DWDATEID INTEGER,
    SHIP_DWDATEID INTEGER,
    SALEPRICE NUMBER(8,2)
);
/
------------------------------1.3--------------------------
drop table GENDERSPELLING;
/
create table GENDERSPELLING (
InvalidValue VARCHAR2(10), 
NewValue VARCHAR2(1)
);
/
INSERT INTO GENDERSPELLING VALUES('MAIL', 'M');
INSERT INTO GENDERSPELLING VALUES('Woman', 'F');
INSERT INTO GENDERSPELLING VALUES('Fem', 'F');
INSERT INTO GENDERSPELLING VALUES('Female', 'F');
INSERT INTO GENDERSPELLING VALUES('Male', 'M');
INSERT INTO GENDERSPELLING VALUES('Gentleman', 'M');
INSERT INTO GENDERSPELLING VALUES('MM', 'M');
INSERT INTO GENDERSPELLING VALUES('FF', 'F');
INSERT INTO GENDERSPELLING VALUES('FEMAIL', 'F');
/
------------------------------2.1--------------------------

INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2PRODUCT',116,1,TO_DATE(SYSDATE,'yyyy-mm-dd'),'SKIP'
FROM A2Product P 
WHERE P.PRODNAME IS NULL;
commit;
/
------------------------------2.2--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2PRODUCT',129,2,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2Product PD 
WHERE PD.MANUFACTURERCODE IS NULL;
commit;
/
------------------------------2.3--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2PRODUCT',141,3,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2Product PD 
WHERE PD.PRODCATEGORY IS NULL OR PD.PRODCATEGORY NOT IN 
(SELECT PCT.PRODUCTCATEGORY FROM A2PRODCATEGORY PCT);
commit;
/
------------------------------2.4.3--------------------------
INSERT INTO DWPROD
SELECT SEQ_DWPROD.NEXTVAL, 'A2PRODUCT', PRODID, PRODNAME, CATEGORYNAME, MANUNAME,
DESCRIPTION
FROM A2PRODUCT PD
NATURAL JOIN A2MANUFACTURER MF, A2SHIPPING SP, A2PRODCATEGORY PCT
WHERE PD.ROWID NOT IN 
(SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV) 
AND MF.MANUCODE= PD.MANUFACTURERCODE 
AND PCT.PRODUCTCATEGORY = PD.PRODCATEGORY 
AND SP.SHIPPINGCODE = PD.SHIPPINGCODE;
COMMIT;
/
------------------------------2.4.4--------------------------
INSERT INTO DWPROD
SELECT SEQ_DWPROD.NEXTVAL, 'A2PRODUCT', PRODID, PRODNAME, CATEGORYNAME, 'UNKNOWN',
DESCRIPTION
FROM A2PRODUCT PD
NATURAL JOIN A2PRODCATEGORY PCT, A2SHIPPING SP
WHERE PD.ROWID IN 
(SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 2 )  
AND PCT.PRODUCTCATEGORY = PD.PRODCATEGORY 
AND SP.SHIPPINGCODE = PD.SHIPPINGCODE;
COMMIT;
/
------------------------------2.4.5--------------------------
INSERT INTO DWPROD
SELECT SEQ_DWPROD.NEXTVAL, 'A2PRODUCT', PRODID, PRODNAME, 'UNKNOWN', MANUNAME,
DESCRIPTION
FROM A2PRODUCT PD
NATURAL JOIN A2MANUFACTURER MF, A2SHIPPING SP
WHERE PD.ROWID IN 
(SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 3 )  
AND MF.MANUCODE= PD.MANUFACTURERCODE
AND SP.SHIPPINGCODE = PD.SHIPPINGCODE;
COMMIT;
/
------------------------------3.1--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2CUSTBRIS',168,4,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2CUSTBRIS CBR 
WHERE CBR.CUSTCATCODE NOT IN
(SELECT CCT.CUSTCATCODE FROM A2CUSTCATEGORY CCT) 
OR CBR.CUSTCATCODE IS NULL;
commit;
/
------------------------------3.2--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2CUSTBRIS',196,5,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2CUSTBRIS CBR
WHERE CBR.PHONE LIKE '%-%' OR CBR.PHONE LIKE '% %'; 
commit;
/
------------------------------3.3--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2CUSTBRIS',204,6,TO_DATE(SYSDATE,'yyyy-mm-dd'),'SKIP'
FROM A2CUSTBRIS CBR 
WHERE (NOT(CBR.PHONE LIKE '%-%' OR CBR.PHONE LIKE '% %')) AND LENGTH(CBR.PHONE) != 10; 
commit;
/
-----------------------------3.4--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2CUSTBRIS',231,7,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2CUSTBRIS CBR 
WHERE NOT(UPPER(CBR.GENDER) LIKE 'M' OR UPPER(CBR.GENDER) LIKE 'F') OR CBR.GENDER IS NULL; 
commit;
/
-----------------------------3.5.1--------------------------
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, 
POSTCODE, CITY, STATE, CUSTCATNAME) 
 SELECT SEQ_DWCUST.NEXTVAL, CUSTID, FNAME, SNAME, UPPER(GENDER), PHONE, POSTCODE, CITY, 
CBR.STATE, CUSTCATNAME 
 FROM A2CUSTBRIS CBR 
 NATURAL JOIN A2CUSTCATEGORY 
 WHERE CBR.ROWID NOT IN 
 (SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV); 
 COMMIT;
/
-----------------------------3.5.2--------------------------
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, 
POSTCODE, CITY, STATE, CUSTCATNAME) 
 SELECT SEQ_DWCUST.NEXTVAL, CUSTID, FNAME, SNAME, UPPER(GENDER), PHONE, POSTCODE, CITY, 
CBR.STATE, 'UNKNOWN'
 FROM A2CUSTBRIS CBR 
 WHERE CBR.ROWID IN 
 (SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 4); 
COMMIT;
/
-----------------------------3.5.3--------------------------
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, 
POSTCODE, CITY, STATE, CUSTCATNAME) 
 SELECT SEQ_DWCUST.NEXTVAL, CUSTID, FNAME, SNAME, UPPER(GENDER),
 REPLACE(REPLACE(PHONE,' ',''),'-',''), POSTCODE, CITY, 
CBR.STATE,CUSTCATNAME
 FROM A2CUSTBRIS CBR 
 NATURAL JOIN A2CUSTCATEGORY
 WHERE CBR.ROWID IN 
 (SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 5); 
COMMIT;
/
-----------------------------3.5.4--------------------------
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, FIRSTNAME, SURNAME, GENDER, PHONE, 
POSTCODE, CITY, STATE, CUSTCATNAME) 
 SELECT SEQ_DWCUST.NEXTVAL, CUSTID, FNAME, SNAME, 
 
 CASE WHEN UPPER(GENDER) IN (SELECT INVALIDVALUE FROM GENDERSPELLING) THEN
 (SELECT NEWVALUE FROM GENDERSPELLING GSP WHERE UPPER(CBR.GENDER) = 
  GSP.INVALIDVALUE)
  ELSE 'U'
  END,
  
 PHONE, POSTCODE, CITY, 
 CBR.STATE,CUSTCATNAME
 FROM A2CUSTBRIS CBR 
 NATURAL JOIN A2CUSTCATEGORY
 WHERE CBR.ROWID IN 
 (SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 7); 
COMMIT;
/
-----------------------------4.1--------------------------
MERGE INTO DWCUST DCT
USING (SELECT * FROM A2CUSTMELB CM INNER JOIN A2CUSTCATEGORY CT 
ON CM.CUSTCATCODE = CT.CUSTCATCODE) CM
ON 
(DCT.FIRSTNAME = CM.FNAME 
AND DCT.SURNAME = CM.SNAME 
AND DCT.POSTCODE=CM.POSTCODE)

WHEN MATCHED THEN UPDATE SET DCT.DWSOURCEIDMELB = CM.CUSTID
WHEN NOT MATCHED THEN INSERT (DWCUSTID,DWSOURCEIDMELB,FIRSTNAME, SURNAME, GENDER,
PHONE, POSTCODE, CITY, STATE, CUSTCATNAME)
VALUES (SEQ_DWCUST.NEXTVAL,CM.CUSTID,CM.FNAME,CM.SNAME,UPPER(CM.GENDER),CM.PHONE,
CM.POSTCODE, CM.CITY, CM.STATE, CM.CUSTCATNAME);
COMMIT;
/
-----------------------------5.1--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2SALEBRIS',247,8,TO_DATE(SYSDATE,'yyyy-mm-dd'),'SKIP'
FROM A2SALEBRIS SBR 
WHERE SBR.PRODID NOT IN 
 (SELECT DP.DWSOURCEID FROM DWPROD DP) 
OR SBR.PRODID IS NULL;
commit;
/
-----------------------------5.2--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2SALEBRIS',272,9,TO_DATE(SYSDATE,'yyyy-mm-dd'),'SKIP'
FROM A2SALEBRIS SBR 
WHERE NOT EXISTS 
(SELECT NULL FROM DWCUST DC WHERE SBR.CUSTID = DC.DWSOURCEIDBRIS );
commit;
/
-----------------------------5.3--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2SALEBRIS',294,10,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2SALEBRIS SBR 
WHERE SBR.SHIPDATE < SBR.SALEDATE;
commit;
/
-----------------------------5.4--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2SALEBRIS',317,11,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2SALEBRIS SBR 
WHERE sbr.unitprice IS NULL;
commit;
/
-----------------------------5.5--------------------------
INSERT INTO DWSALE(DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, QTY, SALE_DWDATEID,
SHIP_DWDATEID, SALEPRICE)

SELECT SEQ_DWSALE.NEXTVAL,
(SELECT DWCUSTID FROM DWCUST WHERE DWSOURCEIDBRIS =SBR.CUSTID),
(SELECT DWPRODID FROM DWPROD WHERE DWSOURCEID =SBR.PRODID),
SBR.SALEID,
SBR.QTY,
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SBR.SALEDATE),
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SBR.SHIPDATE),
SBR.UNITPRICE

FROM A2SALEBRIS SBR
WHERE ROWID NOT IN 
(SELECT SOURCE_ROWID FROM A2ERROREVENT);
COMMIT;
/
-----------------------------5.6--------------------------
INSERT INTO DWSALE(DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, QTY, SALE_DWDATEID,
SHIP_DWDATEID, SALEPRICE)

SELECT SEQ_DWSALE.NEXTVAL,
(SELECT DWCUSTID FROM DWCUST WHERE DWSOURCEIDBRIS =SBR.CUSTID),
(SELECT DWPRODID FROM DWPROD WHERE DWSOURCEID =SBR.PRODID),
SBR.SALEID,
SBR.QTY,
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SBR.SALEDATE),
((SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SBR.SALEDATE)+2),
SBR.UNITPRICE

FROM A2SALEBRIS SBR
WHERE ROWID IN 
(SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 10);
COMMIT;
/
-----------------------------5.7--------------------------
INSERT INTO DWSALE(DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, QTY, SALE_DWDATEID,
SHIP_DWDATEID, SALEPRICE)

SELECT SEQ_DWSALE.NEXTVAL,
(SELECT DWCUSTID FROM DWCUST WHERE DWSOURCEIDBRIS =SBR.CUSTID),
(SELECT DWPRODID FROM DWPROD WHERE DWSOURCEID =SBR.PRODID),
SBR.SALEID,
SBR.QTY,
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SBR.SALEDATE),
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SBR.SHIPDATE),
(SELECT MAX(SBR.UNITPRICE) FROM A2SALEBRIS SBR WHERE SBR.PRODID = DWP.DWSOURCEID)

FROM A2SALEBRIS SBR
INNER JOIN DWPROD DWP ON SBR.PRODID = DWP.DWSOURCEID
WHERE SBR.ROWID IN 
(SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 11);
COMMIT;
/
-----------------------------6.1--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2SALEMELB',325,12,TO_DATE(SYSDATE,'yyyy-mm-dd'),'SKIP'
FROM A2SALEMELB SMB 
WHERE SMB.PRODID NOT IN
(SELECT DWPROD. DWSOURCEID FROM DWPROD);
commit;
/
-----------------------------6.2--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2SALEMELB',346,13,TO_DATE(SYSDATE,'yyyy-mm-dd'),'SKIP'
FROM A2SALEMELB SMB 
WHERE SMB.CUSTID NOT IN
(SELECT DWCUST. DWSOURCEIDMELB FROM DWCUST 
WHERE DWCUST.DWSOURCEIDMELB IS NOT NULL) 
OR SMB.CUSTID IS NULL;
commit;
/
-----------------------------6.3--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2SALEMELB',379,14,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2SALEMELB SMB 
WHERE SMB.SALEDATE > SMB.SHIPDATE;
commit;
/
-----------------------------6.4--------------------------
INSERT INTO A2ERROREVENT
SELECT SEQ_A2ERROREVENT.NEXTVAL, ROWID,'A2SALEMELB',391,15,TO_DATE(SYSDATE,'yyyy-mm-dd'),'MODIFY'
FROM A2SALEMELB SMB 
WHERE SMB.UNITPRICE IS NULL;
commit;
/
-----------------------------6.5--------------------------
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDMELB, QTY, SALE_DWDATEID,
SHIP_DWDATEID, SALEPRICE)

SELECT SEQ_DWSALE.NEXTVAL,
(SELECT DWCUSTID FROM DWCUST WHERE DWSOURCEIDMELB = SMB.CUSTID),
(SELECT DWPRODID FROM DWPROD WHERE DWSOURCEID = SMB.PRODID),
SMB.SALEID,
SMB.QTY,
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SMB.SALEDATE),
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SMB.SHIPDATE),
SMB.UNITPRICE

FROM A2SALEMELB SMB
WHERE ROWID NOT IN 
(SELECT SOURCE_ROWID FROM A2ERROREVENT);
COMMIT;
/
-----------------------------6.6--------------------------
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDMELB, QTY, SALE_DWDATEID,
SHIP_DWDATEID, SALEPRICE)

SELECT SEQ_DWSALE.NEXTVAL,
(SELECT DWCUSTID FROM DWCUST WHERE DWSOURCEIDMELB = SMB.CUSTID),
(SELECT DWPRODID FROM DWPROD WHERE DWSOURCEID = SMB.PRODID),
SMB.SALEID,
SMB.QTY,
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SMB.SALEDATE),
((SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SMB.SALEDATE)+2),
SMB.UNITPRICE

FROM A2SALEMELB SMB
WHERE ROWID IN 
(SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 14);
COMMIT;
/
-----------------------------6.7--------------------------
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDMELB, QTY, SALE_DWDATEID,
SHIP_DWDATEID, SALEPRICE)

SELECT SEQ_DWSALE.NEXTVAL,
(SELECT DWCUSTID FROM DWCUST WHERE DWSOURCEIDMELB = SMB.CUSTID),
(SELECT DWPRODID FROM DWPROD WHERE DWSOURCEID = SMB.PRODID),
SMB.SALEID,
SMB.QTY,
(SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SMB.SALEDATE),
((SELECT DATEKEY FROM DWDATE WHERE DATEVALUE = SMB.SHIPDATE)),
(SELECT MAX(SMB.UNITPRICE) FROM A2SALEMELB SMB WHERE SMB.PRODID = DWP.DWSOURCEID)

FROM A2SALEMELB SMB
INNER JOIN DWPROD DWP ON SMB.PRODID = DWP.DWSOURCEID
WHERE SMB.ROWID IN 
(SELECT EV.SOURCE_ROWID FROM A2ERROREVENT EV WHERE EV.FILTERID = 15);
COMMIT;
/
-----------------------------7.1--------------------------
DELETE FROM DWSALE DSL
WHERE DSL.DWSOURCEIDMELB 
IN 
(SELECT SALEID As DWSOURCEIDMELB FROM A2SALEMELB SMB
WHERE SMB.ROWID IN 
(SELECT SOURCE_ROWID FROM A2ERROREVENT 
WHERE SOURCE_TABLE = 'A2SALEMELB'
GROUP BY SOURCE_ROWID 
HAVING COUNT(SOURCE_ROWID)>1)
);
/
-----------------------------8.A--------------------------
select to_char(DDT.datevalue, 'DAY') as "WEEKDAY", 
sum(DSL.qty * DSL.saleprice) as "Total Sale"
from DWSALE DSL
inner join DWDATE DDT on DSL.sale_dwdateid = DDT.datekey
group by to_char(DDT.datevalue, 'DAY')
order by SUM(DSL.QTY * DSL.SALEPRICE) desc;
/
-----------------------------8.B--------------------------
SELECT DWCUST.CUSTCATNAME AS "CUSTCATNAME",
SUM(DWSALE.qty * DWSALE.saleprice) as "TOTALSALES"
FROM DWSALE
INNER JOIN DWCUST ON DWSALE.DWCUSTID = DWCUST.DWCUSTID
GROUP BY CUSTCATNAME
ORDER BY SUM(DWSALE.QTY * DWSALE.SALEPRICE) ASC;
/
-----------------------------8.C--------------------------
SELECT DWPROD.PRODMANUNAME AS "PRODMANUNAME",
SUM(DWSALE.QTY) as "TOTAL QTY SOLD"
FROM DWSALE
INNER JOIN DWPROD ON DWSALE.DWPRODID = DWPROD.DWPRODID
GROUP BY PRODMANUNAME
ORDER BY SUM(DWSALE.QTY) DESC;
/
-----------------------------8.D--------------------------
SELECT DWC.DWCUSTID AS "DWCUSTID",
DWC.FIRSTNAME AS "FIRSTNAME",
DWC.SURNAME AS "SURNAME",
SUM(DWSALE.qty * DWSALE.saleprice) as "TOTALSALES"
FROM DWSALE
INNER JOIN DWCUST DWC ON DWSALE.DWCUSTID = DWC.DWCUSTID
GROUP BY DWC.DWCUSTID,DWC.FIRSTNAME,DWC.SURNAME
ORDER BY SUM(DWSALE.QTY * DWSALE.SALEPRICE) DESC
FETCH FIRST 10 ROWS ONLY;
/
-----------------------------8.E--------------------------
SELECT DWP.DWPRODID AS "DWPRODID",
DWP.PRODNAME AS "PRODNAME",
SUM(DWSALE.qty) as "TOTALSALES"
FROM DWSALE
INNER JOIN DWPROD DWP ON DWSALE.DWPRODID = DWP.DWPRODID
GROUP BY DWP.DWPRODID, DWP.PRODNAME
ORDER BY SUM(DWSALE.QTY) ASC
FETCH FIRST 10 ROWS ONLY;
/
-----------------------------8.F--------------------------
select STATE, CITY, sum(dws.qty * dws.saleprice) as "Total Sale"
from dwcust dwc
inner join dwsale dws on dwc.dwcustid = dws.dwcustid
group by dwc.CITY, dwc.STATE
order by dwc.STATE asc;
/



